### ISSUE TITLE
Provide example .gitlab-ci.yml extending the AutoDevOps Pipeline

### ISSUE THREAD

**Issue by j-bauer** [nfdi4plants/DataHUB#37]
It's been asked repeatedly if it is possible to run own CI-Jobs without loosing the AutoDevOps features. This example shows how:

```
include:
    - template: Auto-DevOps.gitlab-ci.yml

stages:
    - arc_json
    - quality_report_generator
    - quality_report
    - generate_metadata
    - my_own_ci_stuff

My own stuff:
    stage: my_own_ci_stuff
    script:
        - echo "doing things..."
```

Maybe we want to include this in the ARC template repo? Or at least create a KB article for this.

Opinions? @Brilator @kMutagene @muehlhaus @HLWeil
